#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if [ -z "`id -u gg-user 2> /dev/null`" ]; then
        adduser --home /opt/greengrass  --quiet --system --no-create-home \
        --group ggc_group ggc_user || true
    fi
fi
