#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if [ -z "`id -u gg-user 2> /dev/null`" ]; then
        addgroup --system --quiet ggc_group || true
        adduser --home /opt/greengrass --quiet --system --no-create-home \
            --ingroup ggc_group ggc_user || true
    fi
fi
